CREATE DATABASE IF NOT EXISTS shot_counter;
USE shot_counter;

CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  counter INT NOT NULL DEFAULT 0
);
